[general]
dirs = [
    "assets/templates",
    "src/app/auth/io/web/templates",
    "src/app/news/io/web/templates",
    "src/app/team_creation/io/web/templates",
    "src/app/competitions/io/web/templates",
    "src/app/references/io/web/templates",
    "src/app/spaces/io/web/templates",
    "src/app/teams/io/web/templates",
    "src/app/players/io/web/templates",
    "src/web/templates"]