pub mod admin_page;
pub mod dashboard;
pub mod enrollments_tab;
pub mod groups_actions;
pub mod groups_tab;
pub mod groups_widgets;
pub mod schedule_actions;
pub mod schedule_tab;
pub mod schedule_widgets;
